# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.1

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip 
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - curl http://http.debian.net/debian/pool/main/p/php7.1/php7.1_7.1.12-1.debian.tar.xz --output php7.1_7.1.12-1.debian.tar.xz
          - tar xf php7.1_7.1.12-1.debian.tar.xz
          - cd php7.1_7.1.12-1.debian
          - ./configure
          - make install
          - composer install
          - vendor/bin/phpunit ThinbusTestQuick.php